-- Join order with users, order_type, order_status,payment_status,payment_type
SELECT * FROM ORDERS o 
JOIN USERS u ON u.ID_USER = o.CREATED_BY
JOIN ORDER_TYPE ot ON ot.ID_ORDER_TYPE = o.ORDER_TYPE
JOIN ORDER_STATUS os ON os.ID_ORDER_STATUS = o.ORDER_STATUS
JOIN PAYMENT_STATUS ps ON ps.ID_PAYMENT_STATUS = o.PAYMENT_STATUS
JOIN PAYMENT_TYPE pt ON pt.ID_PAYMENT_TYPE = o.PAYMENT_TYPE; 

-- Join order with Order Detail coffe, coffe type users, order_type, order_status,payment_status,payment_type
SELECT * FROM ORDERS o 
JOIN ORDER_DETAIL od ON od.ID_ORDER =o.ID_ORDER
JOIN COFFE c ON c.ID_COFFE = od.ID_COFFE
JOIN COFFE_TYPE ct ON ct.ID_COFFE_TYPE = c.TYPE_COFFE
JOIN USERS u ON u.ID_USER = o.CREATED_BY
JOIN ORDER_TYPE ot ON ot.ID_ORDER_TYPE = o.ORDER_TYPE
JOIN ORDER_STATUS os ON os.ID_ORDER_STATUS = o.ORDER_STATUS
JOIN PAYMENT_STATUS ps ON ps.ID_PAYMENT_STATUS = o.PAYMENT_STATUS
JOIN PAYMENT_TYPE pt ON pt.ID_PAYMENT_TYPE = o.PAYMENT_TYPE; 


