
-- Subquery order by
SELECT o.id_order, 
(SELECT sum(od.AMOUNT_ORDER_DETAIL) FROM ORDER_DETAIL od WHERE od.ID_ORDER = o.ID_ORDER )AS TOTAL_AMOUNT,
(SELECT sum(od.QUANTITY_ORDER_DETAIL) FROM ORDER_DETAIL od WHERE od.ID_ORDER = o.ID_ORDER )AS TOTAL_QTY,
o.CREATED_AT
FROM ORDERS o ORDER BY o.CREATED_AT;

-- sub query group by payment status
SELECT
sum(o.AMOUNT_ORDER) AS AMOUNT,
sum(o.GRAND_TOTAL_ORDER) AS GRAND_TOTAL, 
(SELECT NAME_PAYMENT_STATUS FROM PAYMENT_STATUS WHERE ID_PAYMENT_STATUS = o.PAYMENT_STATUS) AS PAYMENT_STATUS  
FROM ORDERS o GROUP BY o.PAYMENT_STATUS;

-- sub query group by payment type
SELECT
sum(o.AMOUNT_ORDER) AS AMOUNT,
sum(o.GRAND_TOTAL_ORDER) AS GRAND_TOTAL, 
(SELECT NAME_PAYMENT_TYPE FROM PAYMENT_TYPE WHERE ID_PAYMENT_TYPE = o.PAYMENT_TYPE) AS PAYMENT_TYPE
FROM ORDERS o GROUP BY o.PAYMENT_TYPE;